---
title: "treewell_data"
author: "Erika Lee"
date: "2024-05-16"
output: html_document
---

```{r setup, warnings='hide',message=FALSE}
library(tidyverse) # Package with dplyr, tibble, readr, and others to help clean coding
library(dataRetrieval) # Package to download data. 
library(sf) #Geospatial package to plot and explore data
library(mapview) #Simple interface to leaflet interactive maps
library(broom) #Simplifies model outputs
library(knitr) #Makes nice tables
library(kableExtra) #Makes even nicer tables
library(lubridate) #Makes working with dates easier
library(ggthemes) #Makes plots prettier
library(tidyr)
library(readxl)#Makes multiple simultaneous models easier
library(plotly)
library(rstatix)
```

```{r}
setwd("/Volumes/wcnr-network/Research/Kampf/Private/field_data")
```

## Download Prep

Download Data

```{r}
treewell_composite=read_excel("nsf/treewell_data/treewell_data_r.xlsx")
```

## Tidying Dataframe

```{r}
#adjusting date/time, although there is technically no time in this data
treewell_clean <- treewell_composite %>%
  mutate(date = ymd(date, tz = 'MST')) %>%
  #adding in a column with site name
  mutate(site = if_else(str_detect(tree_ID, "tt"), "transitional", "persistent")) %>%
  #reorder columns
  select(c(tree_ID, site, everything()))
```

Creating Dataframes for 5 and 10 cm increment measurements

```{r}
#5cm dataframe
treewell_5cm <- treewell_clean %>%
  filter(increments_cm==5)

#10cm dataframe
treewell_10cm <- treewell_clean %>%
  filter(increments_cm==10)

#persistent dataframe
treewell_pers <- treewell_clean %>%
  filter(site=="persistent")

#transitional dataframe
treewell_trans <- treewell_clean %>%
  filter(site=="transitional")
```

## Data Exploration

```{r}
#initial visualization - all data histogram
treewell_d_hist <- ggplot(data = treewell_clean, aes(x = treewell_diameter)) +
  geom_histogram(binwidth = 5, fill = "skyblue", color = "black") +
  labs(
    title = "Histogram of Treewell Diameter",
    x = "Treewell Diameter (cm)",
    y = "Frequency"
  ) +
  facet_wrap(~date)

print(treewell_d_hist)

#initial visualization - all data scatterplot w/ correlation
dbh_treewell_diameter_plot <- ggplot(data = treewell_clean, aes(x = treewell_diameter, y = dbh)) +
  geom_smooth(method = 'lm', se = TRUE, color = "blue") +
  labs(
    title = "Treewell vs Tree Diameter",
    x = "Treewell Diameter (cm)",
    y = "Tree Diameter (cm)"
  ) +
  geom_point()

ggplotly(dbh_treewell_diameter_plot)
```

## Correlation Test

```{r}
#calculate pearsons correlation coefficient
correlation_result <- cor.test(treewell_clean$treewell_diameter, treewell_clean$dbh)

print(correlation_result)

#interpretation - not a very stong, but positive, pearsons correlation coefficient of 0.415, p-value is statistically significant at the 0.05 value, suggesting there is strong evidence to reject the null hypothesis that the true correlation between treewell diameter and tree diameter is zero. 
```

## Aspect Data Exploration

```{r}
#pivoting the clean dataset longer to have aspect included
treewell_long <- treewell_clean %>%
  select(-c(tree_mort, site)) %>%
  pivot_longer(cols = c(d_edge_N, d_edge_E, d_edge_S, d_edge_W), names_to = "d_edge_aspect", values_to = "d_edge_data") %>%
  pivot_longer(cols = c(sd_tree_N, sd_tree_E, sd_tree_S, sd_tree_W), names_to = "sd_tree_aspect", values_to = "sd_tree_data") %>%
  pivot_longer(cols = c(sd_1_N, sd_1_E, sd_1_S, sd_1_W), names_to = "sd_1_aspect", values_to = "sd_1_data") %>%
  pivot_longer(cols = c(sd_2_N, sd_2_E, sd_2_S, sd_2_W), names_to = "sd_2_aspect", values_to = "sd_2_data") %>%
  pivot_longer(cols = c(sd_3_N, sd_3_E, sd_3_S, sd_3_W), names_to = "sd_3_aspect", values_to = "sd_3_data") %>%
  #adjusting the variable names in the measurement rows
  mutate(d_edge_aspect = case_when(
    str_detect(d_edge_aspect, "N") ~ "N",
    str_detect(d_edge_aspect, "E") ~ "E",
    str_detect(d_edge_aspect, "S") ~ "S",
    str_detect(d_edge_aspect, "W") ~ "W",
    TRUE ~ d_edge_aspect
  )) %>%
  mutate(sd_tree_aspect = case_when(
    str_detect(sd_tree_aspect, "N") ~ "N",
    str_detect(sd_tree_aspect, "E") ~ "E",
    str_detect(sd_tree_aspect, "S") ~ "S",
    str_detect(sd_tree_aspect, "W") ~ "W",
    TRUE ~ sd_tree_aspect
  )) %>%
  mutate(sd_1_aspect = case_when(
    str_detect(sd_1_aspect, "N") ~ "N",
    str_detect(sd_1_aspect, "E") ~ "E",
    str_detect(sd_1_aspect, "S") ~ "S",
    str_detect(sd_1_aspect, "W") ~ "W",
    TRUE ~ sd_1_aspect,
  )) %>%
  mutate(sd_2_aspect = case_when(
    str_detect(sd_2_aspect, "N") ~ "N",
    str_detect(sd_2_aspect, "E") ~ "E",
    str_detect(sd_2_aspect, "S") ~ "S",
    str_detect(sd_2_aspect, "W") ~ "W",
    TRUE ~ sd_2_aspect,
  )) %>%
  mutate(sd_3_aspect = case_when(
    str_detect(sd_3_aspect, "N") ~ "N",
    str_detect(sd_3_aspect, "E") ~ "E",
    str_detect(sd_3_aspect, "S") ~ "S",
    str_detect(sd_3_aspect, "W") ~ "W",
    TRUE ~ sd_3_aspect,
  ))
```

```{r}
#creating aspect dataframes
treewell_n <- treewell_clean %>%
  select(c(tree_ID, site, date, tree_mort, dbh, treewell_diameter, d_edge_N, sd_tree_N, sd_1_N, sd_2_N, sd_3_N, increments_cm))

treewell_e <- treewell_clean %>%
  select(c(tree_ID, site, date, tree_mort, dbh, treewell_diameter, d_edge_E, sd_tree_E, sd_1_E, sd_2_E, sd_3_E, increments_cm))

treewell_s <- treewell_clean %>%
  select(c(tree_ID, site, date, tree_mort, dbh, treewell_diameter, d_edge_S, sd_tree_S, sd_1_S, sd_2_S, sd_3_S, increments_cm))

treewell_w <- treewell_clean %>%
  select(c(tree_ID, site, date, tree_mort, dbh, treewell_diameter, d_edge_W, sd_tree_W, sd_1_W, sd_2_W, sd_3_W, increments_cm))
```

Plotting Aspects

```{r}
treewell_aspects_plot <- ggplot()
```
